### ISSUE TITLE
Getting "panic: runtime error: index out of range"

### ISSUE THREAD

**Issue by agentmilindu** [Nvveen/Gotty#4]
I'm getting this error when trying to invoke `jsonmessage.DisplayJSONMessagesStream` which invokes `Gotty.readTermInfo`. What could be the issue and how I can resolve this? 

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/leopardslab/Dunner/vendor/github.com/Nvveen/Gotty.readTermInfo(0xc0000246a0, 0x1e, 0x0, 0x0, 0x0)
	/home/milindu/go/src/github.com/leopardslab/Dunner/vendor/github.com/Nvveen/Gotty/gotty.go:232 +0xce8
github.com/leopardslab/Dunner/vendor/github.com/Nvveen/Gotty.OpenTermInfo(0xc000024425, 0xe, 0xc000024425, 0xe, 0x12)
	/home/milindu/go/src/github.com/leopardslab/Dunner/vendor/github.com/Nvveen/Gotty/gotty.go:45 +0x287
github.com/leopardslab/Dunner/vendor/github.com/docker/docker/pkg/jsonmessage.DisplayJSONMessagesStream(0x9343e0, 0xc00006c080, 0x9345a0, 0xc0000b0008, 0x1, 0x601, 0x0, 0x0, 0x0)
	/home/milindu/go/src/github.com/leopardslab/Dunner/vendor/github.com/docker/docker/pkg/jsonmessage/jsonmessage.go:263 +0x5b8
github.com/leopardslab/Dunner/pkg/docker.Step.Do(0x7ffef457ef45, 0x5, 0x0, 0x0, 0xc00030a868, 0x4, 0xc000241240, 0x2, 0x2, 0x0, ...)
	/home/milindu/go/src/github.com/leopardslab/Dunner/pkg/docker/docker.go:52 +0x2b3
github.com/leopardslab/Dunner/pkg/dunner.Do(0xc29ce0, 0xc0002b39e0, 0x1, 0x1)
	/home/milindu/go/src/github.com/leopardslab/Dunner/pkg/dunner/dunner.go:31 +0x2a1
github.com/leopardslab/Dunner/vendor/github.com/spf13/cobra.(*Command).execute(0xc29ce0, 0xc0002b39b0, 0x1, 0x1, 0xc29ce0, 0xc0002b39b0)
	/home/milindu/go/src/github.com/leopardslab/Dunner/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/leopardslab/Dunner/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc29f40, 0x0, 0xc2a1a0, 0xc0001fbf68)
	/home/milindu/go/src/github.com/leopardslab/Dunner/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/leopardslab/Dunner/vendor/github.com/spf13/cobra.(*Command).Execute(0xc29f40, 0x0, 0x1)
	/home/milindu/go/src/github.com/leopardslab/Dunner/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/leopardslab/Dunner/cmd.Execute()
	/home/milindu/go/src/github.com/leopardslab/Dunner/cmd/root.go:29 +0x31
main.main()
	/home/milindu/go/src/github.com/leopardslab/Dunner/main.go:8 +0x20
```

**Comment by dbsanfte** [comment]
I am getting this running in a WSL Ubuntu 18.04 terminal on Windows 10.

**Comment by dbsanfte** [comment]
Just tried it on an actual Ubuntu 18.04 VM and I am seeing it there too.
